#!/bin/bash
##### These lines are for Slurm
#SBATCH -N 4
#SBATCH -p pbatch
#SBATCH -t 3:00:00
#SBATCH -A mmbp
#SBATCH -J N2n8_specify_mem


##### These are shell commands
echo 'startig time'
date
mem_per_job=$((1024*128)) # memory perjob, in MB

echo '================ system output of the executable starts here ================'

cd /p/lscratchh/yi10/PRIS/PyPRIS_dif0CL_dif1_CS_DR_top100_tiles/bgSCF8_mu1.0e+02_alpha1.0e-09_thres-15_c03_zrange-100to100_yrange1to45_xrange70to110
chmod u+x pris
srun -N1 -n1 --mem $mem_per_job pris &


cd /p/lscratchh/yi10/PRIS/PyPRIS_dif0CL_dif1_CS_DR_top100_tiles/bgSCF8_mu1.0e+02_alpha1.0e-09_thres-15_c04_zrange-100to100_yrange1to45_xrange105to140
chmod u+x pris
srun -N1 -n1 --mem $mem_per_job pris &


cd /p/lscratchh/yi10/PRIS/PyPRIS_dif0CL_dif1_CS_DR_top100_tiles/bgSCF8_mu1.0e+02_alpha1.0e-09_thres-15_c05_zrange-100to100_yrange1to45_xrange130to175
chmod u+x pris
srun -N1 -n1 --mem $mem_per_job pris &


cd /p/lscratchh/yi10/PRIS/PyPRIS_dif0CL_dif1_CS_DR_top100_tiles/bgSCF8_mu1.0e+02_alpha1.0e-09_thres-15_c06_zrange-100to100_yrange1to45_xrange165to212
chmod u+x pris
srun -N1 -n1 --mem $mem_per_job pris &


cd /p/lscratchh/yi10/PRIS/PyPRIS_dif0CL_dif1_CS_DR_top100_tiles/bgSCF8_mu1.0e+02_alpha1.0e-09_thres-15_c07_zrange-100to100_yrange35to80_xrange1to45
chmod u+x pris
srun -N1 -n1 --mem $mem_per_job pris &


cd /p/lscratchh/yi10/PRIS/PyPRIS_dif0CL_dif1_CS_DR_top100_tiles/bgSCF8_mu1.0e+02_alpha1.0e-09_thres-15_c08_zrange-100to100_yrange35to80_xrange35to80
chmod u+x pris
srun -N1 -n1 --mem $mem_per_job pris &


cd /p/lscratchh/yi10/PRIS/PyPRIS_dif0CL_dif1_CS_DR_top100_tiles/bgSCF8_mu1.0e+02_alpha1.0e-09_thres-15_c09_zrange-100to100_yrange35to80_xrange70to110
chmod u+x pris
srun -N1 -n1 --mem $mem_per_job pris &


cd /p/lscratchh/yi10/PRIS/PyPRIS_dif0CL_dif1_CS_DR_top100_tiles/bgSCF8_mu1.0e+02_alpha1.0e-09_thres-15_c10_zrange-100to100_yrange35to80_xrange105to140
chmod u+x pris
srun -N1 -n1 --mem $mem_per_job pris &

wait

echo '================ system output of the executable ends here ================'
echo '================ system output of the executable ends here ================'
echo ''
echo job id is $id
cd /g/g92/yi10/subtest
touch estimate
echo "#!/bin/bash" >> estimate
echo "seff "$id >> estimate
echo job id is $id
seff $id
chmod u+x estimate
srun -N1 -n1 estimate
echo 'finish time'
date

