#!/bin/bash
##### These lines are for Slurm
#SBATCH -N [NODE NUMBER]
#SBATCH -p [QUEUE TYPE]
#SBATCH -t [RUN TIME]
#SBATCH -A [BANK]
#SBATCH -J [JOB NAME]

##### These are shell commands
echo 'startig time'
date
id=$SLURM_JOBID
echo job id is $id
date
echo '================ system output of the executable starts here ================'
