#!/bin/bash
##### These lines are for Slurm
#SBATCH -N 1
#SBATCH -p pbatch
#SBATCH -t 1:00:00
#SBATCH -A mmbp
#SBATCH -J pris3
#SBATCH -o pris3.out





##### These are shell commands
echo 'startig time'
date

echo '================ system output of the executable starts here ================'

cd /p/lscratchh/yi10/PRIS/PyPRIS_dif0CL_dif1_CS_DR_top100_tiles_50kIt/bgSCF8_mu1.0e+02_alpha1.0e-09_thres-15_c01_zrange-100to100_yrange1to45_xrange1to45
chmod u+x pris
srun -N1 -n1 pris &
cd /p/lscratchh/yi10/PRIS/PyPRIS_dif0CL_dif1_CS_DR_top100_tiles_50kIt/bgSCF8_mu1.0e+02_alpha1.0e-09_thres-15_c02_zrange-100to100_yrange1to45_xrange35to80
chmod u+x pris
srun -N1 -n1 pris &
cd /p/lscratchh/yi10/PRIS/PyPRIS_dif0CL_dif1_CS_DR_top100_tiles_50kIt/bgSCF8_mu1.0e+02_alpha1.0e-09_thres-15_c03_zrange-100to100_yrange1to45_xrange70to110
chmod u+x pris
srun -N1 -n1 pris &

wait

echo '================ system output of the executable ends here ================'
echo 'finish time'

date

##### Notes #####
# in a future upgrade, should make the requested resources to match the size of the dataset.


