#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/tmpris_pieces/count
source $DIR/tmpris_pieces/clean_for_continue
source $DIR/tmpris_pieces/suball
source $DIR/tmpris_pieces/move-final-pris
source $DIR/tmpris_pieces/move-all-png


function tmpris.what
{
  echo functions:
  echo tmpris.count: count for wipeout.
  echo tmpris.clean_for_continue: wipeout
  echo tmpris.suball: submit all existing .sl scripts using sbatch.
  echo tmpris.move-final-pris: move pris results into a destination folder
  echo tmpris.move-all-png: move all png files to the destination folder
  echo tmpris.reset-test: wipe out files generated in a ticket folder in testing phase.
  echo
  echo "type tmpris.<the name> for usage information"
}

function tmpris.reset-test
{
  rm -rf ./debug*
  rm -rf ./saved*obj*
  scp ~/PyPRIS/tools/pris .
  scp ~/PyPRIS/tools/pris_moti .
}
